AZURE_ENVIRONMENT: "AzurePublicCloud"
AZURE_CLIENT_ID: <encoded:>
AZURE_CLIENT_SECRET: <encoded:>
AZURE_CONTROL_PLANE_MACHINE_TYPE: Standard_D2s_v3
AZURE_NODE_MACHINE_TYPE: Standard_D2s_v3
AZURE_ENABLE_PRIVATE_CLUSTER: "true"
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_PLAN: prod
ENABLE_AUDIT_LOGGING: "true"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: oidc
INFRASTRUCTURE_PROVIDER: azure
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
# OIDC values should be filled out for the pinniped example used
OIDC_IDENTITY_PROVIDER_CLIENT_ID: 
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: <encoded:>
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: groups
OIDC_IDENTITY_PROVIDER_ISSUER_URL: 
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: email
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: email
OS_ARCH: amd64
OS_NAME: ubuntu
OS_VERSION: "20.04"
SERVICE_CIDR: 100.64.0.0/13

# replace with Azure KeyVault values
AZURE_CONTROL_PLANE_SUBNET_CIDR: 
AZURE_CONTROL_PLANE_SUBNET_NAME: 
AZURE_FRONTEND_PRIVATE_IP: 
AZURE_LOCATION: 
AZURE_NODE_SUBNET_CIDR: 
AZURE_NODE_SUBNET_NAME: 
AZURE_RESOURCE_GROUP: 
AZURE_SSH_PUBLIC_KEY_B64: 
AZURE_SUBSCRIPTION_ID: 
AZURE_TENANT_ID: 
AZURE_VNET_CIDR: 
AZURE_VNET_NAME: 
AZURE_VNET_RESOURCE_GROUP: 
CLUSTER_NAME: 
# end Azure KeyVault replacements

TKG_HTTP_PROXY_ENABLED: true
TKG_HTTP_PROXY: 
TKG_HTTPS_PROXY: 
TKG_NO_PROXY: 